version: "3.8"

services:

  minecraft_server:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/home:z
    ports:
      - 25565:25565
    env_file:
      - ./cfg.txt
    #restart: always
