
#Power settings
[power]

	#Upgrade Cost Settings
	[power.upgrades]
		#Cost per block for Efficiency 5 upgrade
		#Range: > 0
		upgradeEfficiency5 = 80
		#Cost per Light Block placed
		#Range: > 0
		upgradeLight = 150
		#Cost per block for Silk Touch upgrade
		#Range: > 0
		upgradeSilkCost = 230
		#Cost per block Frozen
		#Range: > 0
		upgradeFreeze = 100
		#Cost per block for Fortune 3 upgrade
		#Range: > 0
		upgradeFortune3 = 300
		#Cost per block for Fortune 1 upgrade
		#Range: > 0
		upgradeFortune1 = 60
		#Cost per block for Fortune 2 upgrade
		#Range: > 0
		upgradeFortune2 = 95
		#Capacity Boost from Battery 1 Upgrade
		#Range: > 0
		battery1 = 200000
		#Capacity Boost from Battery 2 Upgrade
		#Range: > 0
		battery2 = 500000
		#Capacity Boost from Battery 3 Upgrade
		#Range: > 0
		battery3 = 1000000
		#Cost per block for Efficiency 1 upgrade
		#Range: > 0
		upgradeEfficiency1 = 18
		#Cost per block for Efficiency 2 upgrade
		#Range: > 0
		upgradeEfficiency2 = 35
		#Cost per block for Magnet upgrade
		#Range: > 0
		upgradeMagnet = 25
		#Cost per block for Void Junk upgrade
		#Range: > 0
		upgradeVoid = 40
		#Cost per block for Efficiency 3 upgrade
		#Range: > 0
		upgradeEfficiency3 = 45
		#Cost per block for Efficiency 4 upgrade
		#Range: > 0
		upgradeEfficiency4 = 65

	#Mining Gadget Settings
	[power.mining_gadget]
		#Base cost per block broken
		#Range: > 0
		baseCost = 450
		#Maximum power for the Mining Gadget
		#Range: > 0
		maxPower = 100000

